server:
  port: 8087
spring:
  application:
    name: accounts-service

  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/portfolio
    password: 'postgres'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
    default-schema: public
  jackson:
    serialization:
      fail-on-empty-beans: false
eureka:
  client:
    service-url:
      defaultZone: http://admin:!myDiscovery!@localhost:8081/eureka